__author__ = "Patrik Smeds"
__copyright__ = "Copyright 2021, Patrik Smeds"
__email__ = "patrik.smeds@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/pbmarkdup.smk"
include: "rules/fastp.smk"
include: "rules/merged.smk"
include: "rules/sortmerna.smk"


rule all:
    input:
        unpack(compile_output_list),
