# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Patrik Smeds"
__copyright__ = "Copyright , Patrik Smeds"
__email__ = "patrik.smeds@scilifelab.uu.se"
__license__ = "GPL-3"

include: "rules/common.smk"

report: "report/workflow.rst"

rule dummy:
    output:
        "dummy.txt"
    shell:
        """
        touch dummy.txt
        """

rule all:
    input:
        unpack(compile_output_list),
