$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: path to resources.yaml file
  samples:
    type: string
    description: path to samples.tsv file
  units:
    type: string
    description: path to units.tsv file
  default_container:
    type: string
    description: name or path to a default docker/singularity container

  fastp_pe:
    type: object
    description: parameters for fastp_pe
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: |-
          parameters that should be forwarded
          NOTE: Fastp has these options active as default:
          --trim_poly_g
          --qualified_quality_phred 15
          --unqualified_percent_limit 40
          --n_base_limit 5
          --length_required 15

  merged:
    type: object
    description: parameters for merged
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
  
  pbmarkdup:
    type: object
    description: parameters for pbmarkdup
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      log_level:
        type: string
        description: set the logging level for pbmarkdup

  seqtk_subsample:
    type: object
    description: parameters for seqtk_subsample
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      nr_reads_per_fastq:
        type: integer
        description: Number of maximum reads in the subsampled fastq file defined by nr_reads in the config and then divided by number of lanes
      seed:
        type: string
        description: seed for the random generator (must be the same for R1 and R2)

  sortmerna:
    type: object
    description: parameters for sortmerna
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      fasta:
        type: array
        description: list of fasta files containing ribosomal rna sequences
        items:
          type: string
      index:
        type: string
        description: path to index directory

  trimmer_software:
    type: string
    description: choice of trimmer software or none at all
    pattern: "^(fastp_pe|None)$"


required:
  - default_container
  - resources
  - samples
  - trimmer_software
  - units
